services:
  infra-risk-assessment-clickhouse:
    container_name: infra-risk-assessment-clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8323:8123"
      - "9300:9000"
      - "9309:9009"
    volumes:
      - infra-risk-assessment-clickhouse-data:/var/lib/clickhouse
      - infra-risk-assessment-clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-miner}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-miner}
    restart: unless-stopped
    networks:
      - risk-assessment

  infra-risk-assessment-clickhouse-ui:
    container_name: infra-risk-assessment-clickhouse-ui-ui
    image: ghcr.io/caioricciuti/ch-ui:latest
    profiles:
      - utilities
    ports:
      - "5523:5521"
    environment:
      - VITE_CLICKHOUSE_URL=http://infra-risk-assessment-clickhouse:8323/default
      - VITE_CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - VITE_CLICKHOUSE_PASS=${CLICKHOUSE_PASSWORD:-miner}
    depends_on:
      - infra-risk-assessment-clickhouse
    networks:
      - risk-assessment

  srv-worker-risk-assessment:
    container_name: srv-worker-risk-assessment
    image: risk-assessment:latest
    command: >
      celery -A packages.jobs.celery_app worker
      -l info
      -Q risk-assessment-queue
      --concurrency=4
    environment:
      - CLICKHOUSE_HOST=infra-risk-assessment-clickhouse
      - CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-validator}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-validator}
      - METRICS_PORT=8000
      - NX_CUGRAPH_AUTOCONFIG=1
    restart: unless-stopped
    networks:
      - risk-assessment
    depends_on:
      - infra-risk-assessment-clickhouse
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  util-infra-risk-assessment-dozzle:
    container_name: util-infra-risk-assessment-dozzle
    image: amir20/dozzle:latest
    ports:
      - "8999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - risk-assessment

volumes:
  infra-risk-assessment-clickhouse-data:
    name: infra-risk-assessment-clickhouse-data
  infra-risk-assessment-clickhouse-logs:
    name: infra-risk-assessment-clickhouse-logs

networks:
  risk-assessment:
