version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: risk-assessment-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=risk_assessment
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    networks:
      - risk-assessment-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: risk-assessment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - risk-assessment-network
    restart: unless-stopped

  api:
    build:
      context: ../..
      dockerfile: ops/risk-assesment/Dockerfile
    container_name: risk-assessment-api
    command: python -m packages.api.server
    ports:
      - "8000:8000"
    depends_on:
      - clickhouse
      - redis
    env_file:
      - .env
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../../packages:/app/packages
    networks:
      - risk-assessment-network
    restart: unless-stopped

  celery-worker:
    build:
      context: ../..
      dockerfile: ops/risk-assesment/Dockerfile
    container_name: risk-assessment-celery-worker
    command: celery -A packages.jobs.celery_app worker --loglevel=info
    depends_on:
      - redis
      - clickhouse
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    volumes:
      - ../../packages:/app/packages
      - /tmp/sot_data:/tmp/sot_data
    networks:
      - risk-assessment-network
    restart: unless-stopped

  celery-beat:
    build:
      context: ../..
      dockerfile: ops/risk-assesment/Dockerfile
    container_name: risk-assessment-celery-beat
    command: celery -A packages.jobs.celery_app beat --loglevel=info
    depends_on:
      - redis
      - celery-worker
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../../packages:/app/packages
    networks:
      - risk-assessment-network
    restart: unless-stopped

networks:
  risk-assessment-network:
    driver: bridge

volumes:
  clickhouse_data:
  redis_data: